#En Developpement
server:
  port: 9080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecmc?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ''
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true
      file-size-threshold: 2KB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: "Demande Initialisation Importation"
    description: "Api Gestion de Demande Initialisation Importation"
    version: "1.0"

#urlOpay: https://10.3.80.17:8022/opay/?opayin=
urlOpay: http://196.207.202.51:8080/opay/?opayin=

urlApp: "http://localhost:4200"

#En Production
